### ISSUE TITLE
Stream Display does not Initialize

### ISSUE THREAD

**Issue by utcsox** [google-coral/project-teachable#2]
On coral-dev board, Mendel version 3 chef. Ran the following commands as instructed in the ReadMe
```
sh install_requirements.sh
python3 teachable.py --keyboard
```
Attached screen shot below, the expected behavior is that lines of FPS and class should stream, e.g.
`FPS 30.7; #examples: 0; Class One`
 but in my case it appears to be frozen and the only output I see is when I press a key. I am also unable to quit with ctrl-c. I need to reboot the coral dev board. Any help or ideas would be appreciated. Thanks!

<img width="1176" alt="Screen Shot 2019-06-13 at 8 37 25 PM" src="https://user-images.githubusercontent.com/9373908/59481979-99f8ee80-8e1b-11e9-8c27-a194d3ab2c6c.png">

**Comment by mtyka** [comment]
This is likely due to the fact that no camera is connected - I'm able to reproduce exactly this behavior only by disconnecting the camera.
Check that your camera is connected and working:

for Coral Camera:
v4l2-ctl --list-formats
or for external USB camera:
v4l2-ctl -d /dev/video1 --list-formats

should list a bunch of formats

Likewise, you can test the cameras by
sudo apt-get install gstreamer1.0-tools
gst-launch-1.0 v4l2src ! videoconvert ! autovideosink
or
gst-launch-1.0 v4l2src device=/dev/video1 ! videoconvert ! autovideosink

should display a window with the camera stream on the connected hdmi display.
